export const ACCESS_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ORDER_DISPATCHER: "ORDER_DISPATCHER",
  LISTING_MANAGER: "LISTING_MANAGER"
} as const;

export const LOGIN_TYPES = {
  ADMIN: "ADMIN",
  MERCHANT: "MERCHANT"
} as const;